# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c84a6fb02f0809ec21047dbeeb9661bd00617b0d8751121505f79271acbb24bfa7a68de612ade83fa518eaa4bc465fb58edb248238a14f248d5372e36e79ed7

test:
  secret_key_base: fb5b4c4beb2a1b1e878d368bf2e588178022c9b33841ca7517548f72f8dee9f62686654e8b747e3b5215b5224d9bf1e4c33342bc396c69927643229b2bf8c565

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
